# Generated by Django 6.0 on 2025-12-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=120, unique=True)),
                ('password_hash', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(default='usuario', max_length=20)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
